export const customerData = [
  {
    id: '234',
    fullName: 'Ayşe Kaya',
    email: 'ayse.kaya@example.com',
    tenantId: 'cd-34',
    isActive: true,
  },
  {
    id: '456',
    fullName: 'Ali Demir',
    email: 'ali.demir@example.com',
    tenantId: 'ef-56',
    isActive: false,
  },
  {
    id: '789',
    fullName: 'Zeynep Öztürk',
    email: 'zeynep.ozturk@example.com',
    tenantId: 'gh-78',
    isActive: true,
  },
  {
    id: '123',
    fullName: 'Can Yılmaz',
    email: 'can.yilmaz@example.com',
    tenantId: 'ab-12',
    isActive: false,
  },
  {
    id: '987',
    fullName: 'Ece Yıldırım',
    email: 'ece.yildirim@example.com',
    tenantId: 'ij-98',
    isActive: true,
  },
  {
    id: '654',
    fullName: 'Mehmet Aydın',
    email: 'mehmet.aydin@example.com',
    tenantId: 'kl-65',
    isActive: false,
  },
  {
    id: '132',
    fullName: 'Ayşe Kaya',
    email: 'ayse.kaya@example.com',
    tenantId: 'cd-34',
    isActive: true,
  },
  {
    id: '657',
    fullName: 'Ali Demir',
    email: 'ali.demir@example.com',
    tenantId: 'ef-56',
    isActive: false,
  },
  {
    id: '345',
    fullName: 'Zeynep Öztürk',
    email: 'zeynep.ozturk@example.com',
    tenantId: 'gh-78',
    isActive: true,
  },
  {
    id: '896',
    fullName: 'Can Yılmaz',
    email: 'can.yilmaz@example.com',
    tenantId: 'ab-12',
    isActive: false,
  },
  {
    id: '344',
    fullName: 'Ece Yıldırım',
    email: 'ece.yildirim@example.com',
    tenantId: 'ij-98',
    isActive: true,
  },
  {
    id: '994529',
    fullName: 'Mehmet Aydın',
    email: 'mehmet.aydin@example.com',
    tenantId: 'kl-65',
    isActive: false,
  },
  {
    id: '342545',
    fullName: 'Zeynep Öztürk',
    email: 'zeynep.ozturk@example.com',
    tenantId: 'gh-78',
    isActive: true,
  },
  {
    id: '854696',
    fullName: 'Can Yılmaz',
    email: 'can.yilmaz@example.com',
    tenantId: 'ab-12',
    isActive: false,
  },
  {
    id: '312344',
    fullName: 'Ece Yıldırım',
    email: 'ece.yildirim@example.com',
    tenantId: 'ij-98',
    isActive: true,
  },
  {
    id: '544',
    fullName: 'Mehmet Aydın',
    email: 'mehmet.aydin@example.com',
    tenantId: 'kl-65',
    isActive: false,
  },
]
